---

- hosts: dev
  become: true
  tasks:

  - name: installing python pip
    apt:
      name: python-pip
      state: present

  - name: installing docker 
    apt:
      name: docker
      state: present

  - name: start docker
    service:
      name: docker
      state: started
      enabled: yes

  - name: isnatall pythone pip module
    pip:
      name: docker-py
      state: present

  - name: starting the container
    docker_container:
      name: myapp
      image: "chandra78422/myapp:${DOCKER_TAG}"
      state: started
      published_ports:
          - 0.0.0.0:8080:8080
